export interface ServiceField {
  id: string;
  labelAr: string;
  labelEn: string;
  type: "text" | "textarea" | "select" | "date" | "time" | "file";
  required?: boolean;
  optionsAr?: string[];
  optionsEn?: string[];
  placeholderAr?: string;
  placeholderEn?: string;
}

export interface ServiceDefinition {
  slug: string;
  titleAr: string;
  titleEn: string;
  introAr: string;
  introEn: string;
  fields: ServiceField[];
  successAr: string;
  successEn: string;
  mockResultAr: string[];
  mockResultEn: string[];
}

const locationField: ServiceField = { id: "location", labelAr: "الموقع الحالي", labelEn: "Current location", type: "text", required: true, placeholderAr: "اضغط تحديد الموقع أو اكتب الموقع", placeholderEn: "Detect or enter location" };
const photoField: ServiceField = { id: "attachment", labelAr: "صورة أو مستند", labelEn: "Photo or document", type: "file" };

export const SERVICE_CATALOG: Record<string, ServiceDefinition> = {
  queue: { slug: "queue", titleAr: "أخذ رقم انتظار ذكي", titleEn: "Smart Queue", introAr: "اختر الخدمة وسيحسب النظام وقت الانتظار والشباك المناسب.", introEn: "Choose a service to receive a queue number and estimate.", fields: [{ id: "service", labelAr: "الخدمة المطلوبة", labelEn: "Required service", type: "select", required: true, optionsAr: ["خدمات نسك", "الشكاوى", "الإرشاد", "المفقودات", "خدمة عامة"], optionsEn: ["Nusuk services", "Complaints", "Guidance", "Lost & found", "General service"] }], successAr: "تم إصدار رقم الانتظار", successEn: "Queue number issued", mockResultAr: ["رقمك: M-042", "يسبقك: 3 أشخاص", "الانتظار المتوقع: 8 دقائق", "الشباك المتوقع: 4", "سيصلك تنبيه قبل دورك"], mockResultEn: ["Number: M-042", "3 people ahead", "Estimated wait: 8 minutes", "Expected counter: 4", "You will be notified before your turn"] },
  "field-help": { slug: "field-help", titleAr: "الإرشاد للتائهين", titleEn: "Lost Pilgrim Guidance", introAr: "سنحدد بيانات الضيف ومقر سكنه ونرسل أقرب مرشد.", introEn: "We will identify the guest and dispatch the nearest guide.", fields: [{ id: "identity", labelAr: "رقم الجواز أو بطاقة نسك", labelEn: "Passport or Nusuk number", type: "text", required: true }, { id: "destination", labelAr: "الوجهة أو مقر السكن", labelEn: "Destination or accommodation", type: "text", required: true }, locationField], successAr: "تم إرسال طلب الإرشاد", successEn: "Guidance request sent", mockResultAr: ["الطلب: GD-7312", "المرشد: عبدالله", "الوصول المتوقع: 6 دقائق", "الحالة: المرشد في الطريق"], mockResultEn: ["Request: GD-7312", "Guide: Abdullah", "ETA: 6 minutes", "Status: guide on the way"] },
  "instant-translation": { slug: "instant-translation", titleAr: "الترجمة الفورية", titleEn: "Instant Translation", introAr: "تحدث أو اكتب وسيكتشف النظام اللغة ويترجمها فورًا.", introEn: "Speak or type; the system detects and translates the language.", fields: [{ id: "message", labelAr: "النص أو الكلام المراد ترجمته", labelEn: "Text or speech to translate", type: "textarea", required: true }, { id: "accessibility", labelAr: "وضع المساعدة", labelEn: "Assistance mode", type: "select", optionsAr: ["صوت ونص", "نص كبير", "دعم الصم وضعاف السمع"], optionsEn: ["Voice and text", "Large text", "Deaf and hard-of-hearing support"] }], successAr: "اكتملت الترجمة التجريبية", successEn: "Demo translation completed", mockResultAr: ["اللغة المكتشفة: الأردية", "الترجمة: أحتاج مساعدة للوصول إلى الفندق", "التشغيل الصوتي متاح"], mockResultEn: ["Detected language: Urdu", "Translation: I need help reaching the hotel", "Audio playback available"] },
  complaints: { slug: "complaints", titleAr: "الشكاوى", titleEn: "Complaints", introAr: "أدخل تفاصيل الشكوى، ويمكنك التسجيل صوتيًا وإرفاق ملف.", introEn: "Enter complaint details, record voice, or attach a file.", fields: [{ id: "category", labelAr: "تصنيف الشكوى", labelEn: "Complaint category", type: "select", required: true, optionsAr: ["تأخر تقديم الخدمة", "سوء التعامل", "السكن", "الإعاشة", "النقل", "شركة العمرة أو مقدم الخدمة", "مشكلة في تطبيق نسك", "عدم تنفيذ خدمة", "أخرى"], optionsEn: ["Service delay", "Staff conduct", "Accommodation", "Catering", "Transport", "Umrah company/provider", "Nusuk app", "Service not delivered", "Other"] }, { id: "details", labelAr: "تفاصيل الشكوى", labelEn: "Complaint details", type: "textarea", required: true }, locationField, photoField], successAr: "تم إرسال الشكوى", successEn: "Complaint submitted", mockResultAr: ["الرقم المرجعي: CMP-20481", "الحالة: قيد المراجعة", "الوقت المتوقع للرد: 24 ساعة"], mockResultEn: ["Reference: CMP-20481", "Status: under review", "Expected response: 24 hours"] },
  reports: { slug: "reports", titleAr: "البلاغات العامة", titleEn: "General Reports", introAr: "سيصنف مِنار البلاغ ويوجهه إلى الجهة المختصة.", introEn: "Minar will classify and route the report.", fields: [{ id: "type", labelAr: "نوع البلاغ", labelEn: "Report type", type: "select", required: true, optionsAr: ["شخص تائه", "طفل مفقود", "حالة صحية طارئة", "شخص يحتاج مساعدة", "ازدحام شديد", "عائق في مسار", "خطر أمني أو سلامة", "نظافة أو مرفق", "تعطل جهاز", "العثور على غرض", "بلاغ آخر"], optionsEn: ["Lost person", "Missing child", "Medical emergency", "Person needs help", "Severe crowd", "Route obstruction", "Security/safety", "Facility issue", "Kiosk failure", "Found item", "Other"] }, { id: "details", labelAr: "وصف البلاغ", labelEn: "Report details", type: "textarea", required: true }, locationField, photoField], successAr: "تم توجيه البلاغ", successEn: "Report routed", mockResultAr: ["البلاغ: RPT-8831", "التصنيف التجريبي: سلامة ميدانية", "الجهة: مركز العمليات الموحد", "الحالة: تم الاستلام"], mockResultEn: ["Report: RPT-8831", "Demo classification: field safety", "Destination: unified operations", "Status: received"] },
  "lost-person": { slug: "lost-person", titleAr: "الأشخاص المفقودون", titleEn: "Missing Persons", introAr: "سجّل بيانات الشخص وآخر موقع شوهد فيه.", introEn: "Enter the person's details and last seen location.", fields: [{ id: "name", labelAr: "الاسم", labelEn: "Name", type: "text", required: true }, { id: "age", labelAr: "العمر", labelEn: "Age", type: "text", required: true }, { id: "nationality", labelAr: "الجنسية واللغة", labelEn: "Nationality and language", type: "text" }, locationField, { id: "lostTime", labelAr: "وقت الفقد", labelEn: "Time missing", type: "time" }, { id: "health", labelAr: "الحالة الصحية", labelEn: "Health condition", type: "textarea" }, photoField, { id: "reporter", labelAr: "بيانات المبلّغ", labelEn: "Reporter details", type: "text", required: true }], successAr: "تم إنشاء بلاغ المفقود", successEn: "Missing-person report created", mockResultAr: ["رقم البلاغ: MP-1459", "الحالة: جارٍ البحث", "آخر تحديث: تمت مشاركة البلاغ مع الفرق الميدانية"], mockResultEn: ["Report: MP-1459", "Status: searching", "Latest: shared with field teams"] },
  "lost-items": { slug: "lost-items", titleAr: "المفقودات والمعثورات", titleEn: "Lost & Found", introAr: "اختر تسجيل مفقود أو معثور عليه لتشغيل المطابقة الذكية.", introEn: "Register a lost or found item for smart matching.", fields: [{ id: "path", labelAr: "المسار", labelEn: "Path", type: "select", required: true, optionsAr: ["غرض مفقود", "غرض تم العثور عليه"], optionsEn: ["Lost item", "Found item"] }, { id: "itemType", labelAr: "نوع الغرض", labelEn: "Item type", type: "text", required: true }, { id: "description", labelAr: "الوصف والتفاصيل", labelEn: "Description", type: "textarea", required: true }, locationField, { id: "eventTime", labelAr: "الوقت", labelEn: "Time", type: "time" }, photoField], successAr: "تم تسجيل الغرض وتشغيل المطابقة", successEn: "Item registered and matching started", mockResultAr: ["الرقم: LF-7724", "تطابق تجريبي محتمل: 87%", "الموقع المقترح: مركز مفقودات الحرم", "الحالة: بانتظار التحقق"], mockResultEn: ["Reference: LF-7724", "Potential demo match: 87%", "Suggested location: Haram Lost & Found", "Status: verification pending"] },
  "nusuk-services": { slug: "nusuk-services", titleAr: "خدمات تطبيق نسك", titleEn: "Nusuk App Services", introAr: "اختر الإجراء المتعلق بالحساب أو التصريح.", introEn: "Choose an account or permit action.", fields: [{ id: "action", labelAr: "الخدمة", labelEn: "Service", type: "select", required: true, optionsAr: ["عرض بيانات الحساب", "تحديث بيانات التواصل", "عرض التصاريح", "التحقق من التصريح", "طباعة تصريح", "استرجاع الحساب", "رفع طلب دعم"], optionsEn: ["View account", "Update contact", "View permits", "Check permit", "Print permit", "Recover account", "Support request"] }, { id: "passport", labelAr: "رقم الجواز أو التأشيرة", labelEn: "Passport or visa number", type: "text", required: true }], successAr: "تم تنفيذ المحاكاة", successEn: "Demo action completed", mockResultAr: ["الحساب: نشط", "التصريح: ساري", "رقم التصريح: NSK-550218", "الطباعة التجريبية جاهزة"], mockResultEn: ["Account: active", "Permit: valid", "Permit: NSK-550218", "Demo print ready"] },
  udhiyah: { slug: "udhiyah", titleAr: "خدمة الأضاحي", titleEn: "Adahi Service", introAr: "اختر نوع النسك وأكمل عملية دفع تجريبية.", introEn: "Choose the offering and complete a demo payment.", fields: [{ id: "type", labelAr: "نوع النسك أو الأضحية", labelEn: "Offering type", type: "select", required: true, optionsAr: ["هدي تمتع أو قران — 720 ر.س", "فدية — 180 ر.س", "أضحية — 850 ر.س"], optionsEn: ["Hady — SAR 720", "Fidya — SAR 180", "Udhiyah — SAR 850"] }, { id: "name", labelAr: "اسم صاحب النسك", labelEn: "Guest name", type: "text", required: true }], successAr: "نجحت عملية الدفع التجريبية", successEn: "Demo payment successful", mockResultAr: ["السند: ADH-903311", "الحالة: مدفوع تجريبيًا", "يمكن طباعة السند أو إرساله"], mockResultEn: ["Receipt: ADH-903311", "Status: demo paid", "Receipt can be printed or sent"] },
  "religious-guide": { slug: "religious-guide", titleAr: "الدليل الديني والمحتوى الإثرائي", titleEn: "Religious & Enrichment Guide", introAr: "اختر المحتوى المطلوب وسيظهر بلغة المستخدم.", introEn: "Choose trusted guidance in the user's language.", fields: [{ id: "topic", labelAr: "الموضوع", labelEn: "Topic", type: "select", required: true, optionsAr: ["دليل العمرة", "دليل الحج", "تعليمات المناسك", "الأدعية", "الأسئلة الشائعة", "المواقع التاريخية والثقافية"], optionsEn: ["Umrah guide", "Hajj guide", "Ritual instructions", "Supplications", "FAQ", "Historical sites"] }], successAr: "تم تحميل المحتوى المعتمد", successEn: "Trusted content loaded", mockResultAr: ["المصدر التجريبي: قاعدة معرفة مِنار المعتمدة", "يتوفر شرح نصي وصوتي", "يتوفر مقطع إرشادي قصير"], mockResultEn: ["Demo source: trusted Minar knowledge base", "Text and audio available", "Short guidance video available"] },
  "help-me": { slug: "help-me", titleAr: "ساعدني", titleEn: "Help Me", introAr: "اطلب مساعدة فورية وسيشارك النظام موقعك مع فريق الدعم.", introEn: "Request immediate help and share your location.", fields: [{ id: "case", labelAr: "نوع الحالة", labelEn: "Case type", type: "select", required: true, optionsAr: ["تائه", "حالة صحية", "مساعدة لذوي الإعاقة", "خطر أو سلامة", "التحدث مع موظف"], optionsEn: ["Lost", "Medical", "Accessibility help", "Safety", "Speak to staff"] }, locationField, { id: "notes", labelAr: "تفاصيل مختصرة", labelEn: "Brief details", type: "textarea" }], successAr: "تم طلب المساعدة", successEn: "Help requested", mockResultAr: ["الطلب: HELP-9112", "الفريق الميداني في الطريق", "الوصول المتوقع: 4 دقائق", "الاتصال التجريبي بموظف الدعم متاح"], mockResultEn: ["Request: HELP-9112", "Field team dispatched", "ETA: 4 minutes", "Demo support call available"] },
  transport: { slug: "transport", titleAr: "النقل والمواصلات", titleEn: "Transport", introAr: "اختر الوجهة ووسيلة النقل المناسبة.", introEn: "Choose a destination and suitable transport.", fields: [{ id: "destination", labelAr: "الوجهة", labelEn: "Destination", type: "text", required: true }, { id: "mode", labelAr: "وسيلة النقل", labelEn: "Transport mode", type: "select", required: true, optionsAr: ["حافلة", "قطار", "مركبة أجرة", "مسار مشي مهيأ"], optionsEn: ["Bus", "Train", "Taxi", "Accessible walking route"] }, { id: "accessible", labelAr: "احتياج وصول", labelEn: "Accessibility need", type: "select", optionsAr: ["لا يوجد", "كرسي متحرك", "كبير سن", "ضعف بصري"], optionsEn: ["None", "Wheelchair", "Senior", "Visual impairment"] }], successAr: "تم العثور على المسار", successEn: "Route found", mockResultAr: ["أقرب نقطة تجمع: بوابة 6", "الوصول: 7 دقائق", "موعد الحافلة: بعد 11 دقيقة", "الازدحام المتوقع: متوسط"], mockResultEn: ["Nearest pickup: Gate 6", "Walk: 7 minutes", "Bus: 11 minutes", "Expected crowd: moderate"] },
};

